# Maturin setup for readthedocs, copied from https://www.maturin.rs/sphinx.html
#
# With updates for 
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
    rust: "1.82"

python:
  install:
    - method: pip
      path: .
