name: README Lints

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Check various Rust lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo clippy -- --deny clippy::all
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

  rst:
    name: Validate README
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Run rst2html"
        run: |
          set -e
          pip install docutils
          rst2html --exit 2 README.rst >/dev/null
